version: '3'

services:
  angular-app:
    build: './'
    ports:
      - "4200:4200"
    volumes:
      - ./:/app

  sanity-studio:
    build: './belongings'
    ports:
      - "3333:3333"
    volumes:
      - ./belongings:/studio
